---
- name: SET ANSIBLE_PORT VARIABLE
  set_fact:
    ansible_port: "{{ SSHD_PORT }}"

- name: TRY TO SSH TO ANSIBLE_PORT CONFIGURED PORT
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "5"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: ssh_port

- name: TRY TO SSH TO DEFAULT PORT 22
  wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "5"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: ssh_port_default
  when:
    - ssh_port is defined
    - ssh_port.state is undefined

- name: SET ANSIBLE_PORT TO 22
  set_fact:
    ansible_port: "22"
  when: ssh_port_default.state is defined
