---
- name: COLLECT PRIMARY IP ADDRESS OF MACHINE
  debug:
    msg: "{{ ansible_all_ipv4_addresses | ipaddr() | first | str }}"
  register: ip_validation

- name: SHOW IP BEING TESTED
  debug:
    msg: "{{ ip_validation }}"

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "{{ ip_validation | ipaddr('public') }}"
