---
- name: COLLECT PRIMARY IP ADDRESS OF MACHINE
  debug:
    msg: "{{ ansible_all_ipv4_addresses[0] | ipaddr() }}"
  register: ip_validation

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "ip_validation: {{ ip_validation | ipaddr('public') }}"
