---
- name: GATHERING IP ADDRESSES
  debug:
    msg: "{{ ansible_all_ipv4_addresses | list }}"
  register: ip_addresses

#- name: COLLECT PRIMARY IP ADDRESS OF MACHINE --> MULTIPLE IP
#  debug:
#    msg: "{{ ansible_all_ipv4_addresses[0] | ipaddr('public') }}"
#  register: ip_validation
#  when: "{{ ip_addresses['msg'] | length }} > 1"

- name: COLLECT PRIMARY IP ADDRESS OF MACHINE --> SINGLE IP
  debug:
    msg: "{{ ip_addresses | ipaddr('public') }}"
  register: ip_validation
#  when: "{{ ip_addresses['msg'] | length }} == 1"

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "{{ ip_validation['msg'] | length }} > 0"
