---
- name: GATHERING IP ADDRESSES
  debug:
    msg: "{{ ansible_all_ipv4_addresses | list }}"
  register: ip_addresses

- name: COUNT IP ADDRESSES
  debug:
    msg: "{{ ip_addresses['msg'] | length }} > 1"
  register: multiple_ips

- name: CHECK PRIMARY IP ADDRESS OF MACHINE WITH MULTIPLE IPs
  debug:
    msg: "{{ ansible_all_ipv4_addresses[0] | ipaddr('public') }}"
  register: ip_validation
  when: "{{ multiple_ips }} == True"

- name: CHECK PRIMARY IP ADDRESS OF MACHINE WITH SINGLE IP
  debug:
    msg: "{{ ansible_all_ipv4_addresses | ipaddr('public') }}"
  register: ip_validation
  when: "{{ multiple_ips }} == False"

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "{{ ip_validation['msg'] | length }} > 0"
