---
#- name: GATHERING IP ADDRESSES
#  debug:
#    msg: "{{ ansible_all_ipv4_addresses | list | count }}"
#  register: ip_count

- name: CHECK PRIMARY IP ADDRESS OF MACHINE WITH MULTIPLE IPs
  assert:
    that:
      - "{{ ansible_all_ipv4_addresses[0] | ipaddr('public') }}"
  when: "{{ ansible_all_ipv4_addresses | list | count }} > 1"

- name: CHECK PRIMARY IP ADDRESS OF MACHINE WITH SINGLE IP
  assert:
    that:
      - "{{ ansible_all_ipv4_addresses | ipaddr('public') }}"
  when: "{{ ansible_all_ipv4_addresses | list | count }} == 1"

#- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
#  assert:
#    that:
#      - "{{ ip_validation }}"
