---
- name: DEBUGGING
  debug:
    msg: "{{ ansible_all_ipv4_addresses[0] | ipaddr() }}"
  register: ip_validation

- name: DEBUGGING
  debug:
    msg: "ip_validation: {{ ip_validation }}"

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "{{ ansible_all_ipv4_addresses[0] | ipaddr('public') }}"
