---
- name: DEBUGGING
  debug:
    msg: "IPv4 Address {{ ansible_all_ipv4_addresses }}"

- name: DEBUGGING
  debug:
    msg: "{{ ansible_all_ipv4_addresses | ipaddr('public') }}"
  register: ip_validation

- name: DEBUGGING
  debug:
    msg: "ip_validation: {{ ip_validation }}"

- name: VALIDATE PRIMARY IP OF MACHINE IS A PUBLIC IP
  assert:
    that:
      - "{{ ansible_all_ipv4_addresses | ipaddr('public') }}"
