---
- name: MONITOR SSH
  copy:
    src: templates/jail_ssh.j2
    dest: /etc/fail2ban/jail.d/ssh.conf
    owner: root
    group: root
    mode: 0644

- name: CONFIGURE CONFIG
  copy:
    src: templates/jail_local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: RESTART FAIL2BAN
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes
