---
- hosts: localhost
  pre_tasks:
    - name: ENSURE WE HAVE AT LEAST 3GB FREE OF RAM
      assert:
        that:
          - ansible_memtotal_mb >= 3072

    - name: APT DIST-UPGRADE
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: YUM DIST-UPGRADE
      yum:
        update_cache: yes
        upgrade: dist
      become: yes
      when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

    - name: INSTALL REQUIRED PACKAGES
      package:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ packages }}"

    - name: INSTALL REQUIRED PYTHON MODULES
      pip:
        requirements: "{{ inventory_dir }}/requirements.txt"

  tasks:
    - name: CONFIGURE USER FOR PIRL MASTERNODE SERVICE
      user:
        name: "{{RUNAS_USER}}"
        state: present
        shell: /bin/bash

    - name: UFW
      include_role:
        name: ufw

    - name: PIRL MASTERNODE
      include_role:
        name: pirl_mn
