---
- hosts: localhost
  pre_tasks:
    - name: GET REAL RAM AMOUNT
      shell: grep MemTotal /proc/meminfo |  sed 's/[^0-9]*//g'
      register: total_ram

    - name: OUTPUT RAM AMOUNT
      debug:
        msg: "Your total ram is: {{ total_ram.stdout }}"

    - name: ENSURE WE HAVE AT LEAST 4GB RAM
      assert:
        that:
          - "{{ total_ram.stdout }} >= 4039664"

    - name: APT DIST-UPGRADE
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: YUM UPGRADE
      yum:
        name: '*'
        state: latest
      become: yes
      when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

    - name: INSTALL REQUIRED PACKAGES
      package:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items: "{{ packages }}"

    - name: INSTALL REQUIRED PYTHON MODULES
      pip:
        requirements: "{{ inventory_dir }}/requirements.txt"

  tasks:
    - name: CONFIGURE USER FOR PIRL MASTERNODE SERVICE
      user:
        name: "{{RUNAS_USER}}"
        state: present
        shell: /bin/bash

    - name: UFW
      include_role:
        name: ufw

    - name: PIRL MASTERNODE
      include_role:
        name: pirl_mn
