---
- hosts: localhost
  tasks:
    - name: INCLUDE USER SETTINGS
      include_vars:
        file: env.cfg

    - name: VALIDATE SSH PORT AND UPDATE ANSIBLE ACCORDINGLY
      include_role:
        name: ssh_check

    - name: UPDATE OS AND INSTALL REQUIRED PACKAGES AND MODULES
      include_role:
        name: install_packages

    - name: RUN HARDWARE AND CONFIGURATION CHECKS
      include_role:
        name: "{{ item }}"
      with_items:
        - 'ram_check'
        - 'public_ip_check'
        - 'token_masternode_check'

    - name: CONFIGURE SSHD SERVICE
      include_role:
        name: sshd

    - name: HARDEN THE MACHINE
      include_role:
        name: ufw

    - name: CONFIGURE USER FOR PIRL MASTERNODE SERVICE
      user:
        name: "{{RUNAS_USER}}"
        state: present
        shell: /bin/bash

    - name: PIRL MASTERNODE
      include_role:
        name: pirl_mn

    - name: PIRL CONTENT MASTERNODE
      include_role:
        name: pirl_content_mn
