---
- hosts: localhost
  pre_tasks:
    - name: RUN HARDWARE AND CONFIGURATION CHECKS
      include_role:
        name: "{{ item }}"
        loop:
          - ram_check
          - public_ip_check
          - token_masternode_check

    - name: TOKEN AND MASTERNODE CHECK
      include_role:

    - name: UPDATE OS AND INSTALL REQUIRED PACKAGES AND MODULES
      include_role:
        name: install_packages

  tasks:
    - name: CONFIGURE USER FOR PIRL MASTERNODE SERVICE
      user:
        name: "{{RUNAS_USER}}"
        state: present
        shell: /bin/bash

    - name: UFW
      include_role:
        name: ufw

    - name: PIRL MASTERNODE
      include_role:
        name: pirl_mn
